export const TEMAS_LOJA = [
  {
    id: "tema_padrao",
    nome: "Pêssego MindQuest",
    tipo: "tema",
    preco: 0,
    descricao: "A identidade visual clássica e acolhedora da aplicação.",
    previewBg: "from-[#fff5f0] to-[#fffaf7]",
    corPrimaria: "#E97451",
    iconeCor: "text-[#E97451]",
  },
  {
    id: "tema_lavanda",
    nome: "Lavanda Zen",
    tipo: "tema",
    preco: 80,
    descricao: "Tons suaves de lilás focados em relaxamento e redução da ansiedade.",
    previewBg: "from-[#fbf7ff] to-[#f4ebff]",
    corPrimaria: "#9333ea",
    iconeCor: "text-purple-600",
  },
  {
    id: "tema_menta",
    nome: "Menta Fresca",
    tipo: "tema",
    preco: 120,
    descricao: "Verde esmeralda equilibrado para trazer foco e sensação de clareza.",
    previewBg: "from-[#f2fbf7] to-[#e6f7f0]",
    corPrimaria: "#059669",
    iconeCor: "text-emerald-600",
  },
  {
    id: "tema_oceano",
    nome: "Oceano Profundo",
    tipo: "tema",
    preco: 180,
    descricao: "Azul calmante concebido para dias de intensa sobrecarga mental.",
    previewBg: "from-[#f0f9ff] to-[#e0f2fe]",
    corPrimaria: "#0284c7",
    iconeCor: "text-sky-600",
  },
];